export const GET_DATA_LOADING = 'GET_DATA_LOADING';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_ERROR = 'GET_DATA_ERROR';
export const ADD_EVENTS_LOADING = 'ADD_EVENTS_LOADING';
export const ADD_EVENTS_SUCCESS = 'ADD_EVENTS_SUCCESS';
export const ADD_EVENTS_FAILURE = 'ADD_EVENTS_FAILURE';
export const ADD_TASKS_LOADING = 'ADD_TASKS_LOADING';
export const ADD_TASKS_SUCCESS = 'ADD_TASKS_SUCCESS';
export const ADD_TASKS_FAILURE = 'ADD_TASKS_FAILURE';
export const RESET_EVENTS_SUCCESS = 'RESET_EVENTS_SUCCESS';
export const GET_DATATASKS_SUCCESS = 'GET_DATATASKS_SUCCESS';
export const SET_GOOGLECALENDAR_LOGIN_REQUEST = "SET_GOOGLECALENDAR_LOGIN_REQUEST";
export const SET_GOOGLECALENDAR_LOGIN_SUCCESS = "SET_GOOGLECALENDAR_LOGIN_SUCCESS";
export const SET_GOOGLECALENDAR_LOGIN_FAILURE = "SET_GOOGLECALENDAR_LOGIN_FAILURE";
export const SET_GOOGLECALENDAR_LOGOUT_SUCCESS = "SET_GOOGLECALENDAR_LOGOUT_SUCCESS";



